# https://travis-ci.org/sporteasy/python-facebook
os:
  - linux
  - osx

env:
  global:
    - NEWEST_PYTHON=3.4

language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - pypy3

install:
    - pip install tox>=1.8

script:
  - tox
