# https://travis-ci.org/sporteasy/python-facebook
sudo: false
language: python
python:
  - 2.7
#  - pypy
#  - 3.3
#  - 3.4
#  - 3.5
#  - 3.6
#  - pypy3
os:
  - linux
#  - osx

install:
  - pip install --upgrade setuptools
  - pip install pep8
  - pip install tox-travis

script:
  - tox
  - find . -name \*.py -exec pep8 --ignore=E402 {} +

notifications:
  email: false
