# https://travis-ci.org/sporteasy/python-facebook
sudo: false
language: python
python:
  - 2.7
#  - pypy
#  - 3.3
#  - 3.4
#  - 3.5
#  - 3.6
#  - pypy3
os:
  - linux
#  - osx

#env:
#  global:
#    - NEWEST_PYTHON=3.4

install: pip install tox-travis
#    - pip install tox>=1.8

script: tox

notifications:
  email: false
